DO $$
DECLARE m uuid; a uuid; u uuid; stranger uuid; e public.mosque_enquiries; e2 public.mosque_enquiries; r public.mosque_enquiry_replies; n bigint; replay uuid;
BEGIN
 SELECT mosque_id,user_id INTO m,a FROM public.mosque_admins LIMIT 1;
 SELECT id INTO u FROM auth.users x WHERE email_confirmed_at IS NOT NULL AND NOT coalesce(is_anonymous,false) AND NOT EXISTS(SELECT 1 FROM public.mosque_admins WHERE user_id=x.id) LIMIT 1;
 SELECT id INTO stranger FROM auth.users x WHERE id<>u AND id<>a AND email_confirmed_at IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.mosque_admins ma WHERE ma.user_id=x.id AND ma.mosque_id=m) LIMIT 1;
 ASSERT m IS NOT NULL AND u IS NOT NULL AND stranger IS NOT NULL, 'Fixture identities missing';
 DELETE FROM public.mosque_enquiries WHERE mosque_id=m AND account_id IN(u,stranger);
 DELETE FROM public.mosque_enquiry_settings WHERE mosque_id=m;
 ASSERT NOT has_table_privilege('authenticated','public.mosque_enquiries','UPDATE');
 ASSERT NOT has_table_privilege('authenticated','public.mosque_enquiries','INSERT');
 ASSERT NOT has_table_privilege('anon','public.mosque_enquiries','SELECT');
 ASSERT NOT has_function_privilege('authenticated','public.create_mosque_enquiry(uuid,uuid,uuid,text,text,text,text,text)','EXECUTE');
 ASSERT NOT EXISTS(SELECT 1 FROM public.mosque_enquiry_categories WHERE id IN('ask_imam','personal_support','family_support'));
 BEGIN
 PERFORM public.create_mosque_enquiry(u,gen_random_uuid(),m,'Test User','nikah','Availability','',null);
 RAISE EXCEPTION 'Disabled service accepted'; EXCEPTION WHEN invalid_parameter_value THEN NULL; END;
 e:=public.create_mosque_enquiry(u,gen_random_uuid(),m,'Test User','prayer_facilities','Opening hours','',null);
 ASSERT e.email_verified AND e.contact_email=(SELECT email FROM auth.users WHERE id=u);
 e2:=public.create_mosque_enquiry(u,gen_random_uuid(),m,'Test User','other','Something else','A separate request',null);
 ASSERT e.id<>e2.id;
 replay:=(public.create_mosque_enquiry(u,e.id,m,'Test User','prayer_facilities','Opening hours','',null)).id;
 ASSERT replay=e.id, 'Retry duplicated enquiry';
 BEGIN PERFORM public.reply_mosque_enquiry(stranger,e.id,gen_random_uuid(),'Unauthorised',false); RAISE EXCEPTION 'Wrong owner replied'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN PERFORM public.reply_mosque_enquiry(u,e.id,gen_random_uuid(),'Forged admin',true); RAISE EXCEPTION 'Forged admin replied'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 r:=public.reply_mosque_enquiry(a,e.id,gen_random_uuid(),'Test reply',true);
 ASSERT (SELECT status FROM public.mosque_enquiries WHERE id=e.id)='waiting_for_listener';
 ASSERT NOT EXISTS(SELECT 1 FROM public.mosque_enquiry_replies WHERE enquiry_id=e2.id), 'Replies mixed across enquiries';
 PERFORM set_config('request.jwt.claim.sub',u::text,true); SET LOCAL ROLE authenticated;
 ASSERT (SELECT count(*) FROM public.mosque_enquiries WHERE mosque_id=m)=2;
 BEGIN UPDATE public.mosque_enquiries SET contact_name='Forged'; RAISE EXCEPTION 'Direct update accepted'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN PERFORM public.configure_mosque_enquiries(m,ARRAY['other','nikah']); RAISE EXCEPTION 'Listener configured services'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN PERFORM public.manage_mosque_enquiry(e.id,'resolved'); RAISE EXCEPTION 'Listener changed admin status'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 PERFORM public.manage_mosque_enquiry(e.id,'delete');
 ASSERT NOT EXISTS(SELECT 1 FROM public.mosque_enquiry_replies WHERE enquiry_id=e.id), 'Deleted request replies still visible';
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',a::text,true); SET LOCAL ROLE authenticated;
 ASSERT EXISTS(SELECT 1 FROM public.mosque_enquiries WHERE id=e.id), 'Listener delete removed staff copy';
 PERFORM public.configure_mosque_enquiries(m,ARRAY['other','nikah']);
 PERFORM public.manage_mosque_enquiry(e2.id,'resolved');
 RESET ROLE;
 BEGIN PERFORM public.reply_mosque_enquiry(u,e2.id,gen_random_uuid(),'Closed reply',false); RAISE EXCEPTION 'Closed enquiry accepted reply'; EXCEPTION WHEN invalid_parameter_value THEN NULL; END;
 PERFORM public.create_mosque_enquiry(u,gen_random_uuid(),m,'Test User','nikah','Availability','',null);
 FOR i IN 1..2 LOOP PERFORM public.create_mosque_enquiry(u,gen_random_uuid(),m,'Test User','other','Something else','Limit test',null); END LOOP;
 BEGIN PERFORM public.create_mosque_enquiry(u,gen_random_uuid(),m,'Test User','other','Something else','Limit test',null); RAISE EXCEPTION 'Sixth enquiry accepted'; EXCEPTION WHEN SQLSTATE 'P0429' THEN NULL; END;
 PERFORM set_config('request.jwt.claim.sub',stranger::text,true); SET LOCAL ROLE authenticated;
 ASSERT NOT EXISTS(SELECT 1 FROM public.mosque_enquiries WHERE id IN(e.id,e2.id)), 'Unrelated account can read enquiries';
 ASSERT NOT EXISTS(SELECT 1 FROM public.mosque_enquiry_replies WHERE enquiry_id=e.id), 'Unrelated account can read replies';
 RESET ROLE;
END; $$;
SELECT 'Enquiry ownership, confirmed contact, opt-in categories, separate requests, retries, status, delete and rate-limit checks passed' AS result;
