\set ON_ERROR_STOP on
-- Run ONLY in the disposable database generated by build-compatibility-fixture.py.
insert into auth.users(id) values
 ('30000000-0000-0000-0000-000000000001'),('30000000-0000-0000-0000-000000000002'),('30000000-0000-0000-0000-000000000003'),('30000000-0000-0000-0000-000000000004') on conflict do nothing;
insert into public.users(id,email,role) values
 ('30000000-0000-0000-0000-000000000001','owner@example.invalid','main_admin'),
 ('30000000-0000-0000-0000-000000000002','assigned@example.invalid','user'),
 ('30000000-0000-0000-0000-000000000003','cover@example.invalid','user'),
 ('30000000-0000-0000-0000-000000000004','listener@example.invalid','user');
insert into public.profiles(id) select id from auth.users;
insert into public.mosques(id,name,status,time_zone,live_stream_enabled,live_stream_provider,default_muezzin_user_id)
 values('40000000-0000-0000-0000-000000000001','Compatibility Mosque','active','UTC',true,'livekit','30000000-0000-0000-0000-000000000002');
insert into public.muezzins(user_id,mosque_id) values
 ('30000000-0000-0000-0000-000000000002','40000000-0000-0000-0000-000000000001'),
 ('30000000-0000-0000-0000-000000000003','40000000-0000-0000-0000-000000000001');
insert into public.streams(mosque_id,url) values('40000000-0000-0000-0000-000000000001','https://example.invalid/configured-stream');
insert into public.subscriptions(user_id,mosque_id) values('30000000-0000-0000-0000-000000000004','40000000-0000-0000-0000-000000000001');
insert into public.notification_preferences(user_id,muezzin_duty_reminders_enabled,muezzin_lead_minutes)
 values('30000000-0000-0000-0000-000000000002',true,array[10]),('30000000-0000-0000-0000-000000000003',true,array[10]);
insert into public.notification_preferences(user_id,listener_upcoming_enabled,listener_mosque_scope,listener_lead_minutes)
 values('30000000-0000-0000-0000-000000000004',true,'all_followed',10);

create function public.test_operational_flows() returns void language plpgsql as $$
declare
 m uuid:='40000000-0000-0000-0000-000000000001'; assigned uuid:='30000000-0000-0000-0000-000000000002'; cover_user uuid:='30000000-0000-0000-0000-000000000003';
 t timestamptz:=clock_timestamp(); d date:=(clock_timestamp() at time zone 'UTC')::date; result jsonb; again jsonb; caught boolean; rid uuid;
begin
 insert into prayer_times(mosque_id,date,fajr_adhan_time,source_type) values(m,d,t,'manual')
 on conflict(mosque_id,date) do update set fajr_adhan_time=t,source_type='manual';
 delete from staff_rota where mosque_id=m and date=d;
 insert into staff_rota(mosque_id,staff_user_id,muezzin_user_id,duty_date,date,prayer,prayer_name,adhan_time,notes)
 values(m,assigned,assigned,d,d,'fajr','fajr',t,'Keep this assignment') returning id into rid;
 -- Existing reminder function uses the explicit assignee and saved rota time.
 perform enqueue_due_adhan_reminders_v1(t-interval '10 minutes');
 if not exists(select 1 from notification_events where kind='muezzin_duty' and user_id=assigned and data->>'assignmentSource'='rota') then raise exception 'Explicit rota reminder failed'; end if;
 if not exists(select 1 from notification_events where kind='listener_upcoming' and user_id='30000000-0000-0000-0000-000000000004') then raise exception 'Listener reminder failed'; end if;
 caught:=false;
 begin perform start_live_broadcast_v1(cover_user,m,'fajr',t,null,false,'livekit',null,null,'adhan-'||m||'-fajr-'||d);
 exception when others then caught:=sqlerrm like '%assigned muezzin%'; end;
 if not caught then raise exception 'Unassigned muezzin was allowed to broadcast'; end if;
 result:=start_live_broadcast_v1(assigned,m,'fajr',t,null,false,'livekit',null,null,'adhan-'||m||'-fajr-'||d);
 if not (result->'stream'->>'is_live')::boolean then raise exception 'Assigned live start failed'; end if;
 again:=start_live_broadcast_v1(assigned,m,'fajr',t,null,false,'livekit',null,null,'adhan-'||m||'-fajr-'||d);
 if not (again->>'idempotent')::boolean or again->>'adhanId'<>result->>'adhanId' then raise exception 'Live start retry changed the session'; end if;
 if not exists(select 1 from notification_events where kind='live_adhan' and adhan_id=(result->>'adhanId')::uuid) then raise exception 'Live notification outbox failed'; end if;
 result:=end_live_broadcast_v1(assigned,m,null);
 if (result->>'endedStreamCount')::integer<>1 or (result->>'completedAdhanCount')::integer<>1 then raise exception 'Live end failed'; end if;
 again:=end_live_broadcast_v1(assigned,m,null);
 if not (again->>'idempotent')::boolean then raise exception 'Live end retry failed'; end if;
 -- Approved cover remains eligible, and duty reminders use cover precedence.
 insert into muezzin_cover_requests(mosque_id,date,prayer_name,requester_user_id,original_muezzin_user_id,volunteer_user_id,status)
 values(m,d,'fajr',assigned,assigned,cover_user,'approved');
 perform enqueue_due_adhan_reminders_v1(t-interval '10 minutes');
 if not exists(select 1 from notification_events where kind='muezzin_duty' and user_id=cover_user and data->>'assignmentSource'='cover') then raise exception 'Cover reminder precedence failed'; end if;
 perform start_live_broadcast_v1(cover_user,m,'fajr',t,null,false,'livekit',null,null,'adhan-'||m||'-fajr-'||d);
 perform end_live_broadcast_v1(cover_user,m,null);
 delete from muezzin_cover_requests where mosque_id=m;
 delete from staff_rota where id=rid;
 perform enqueue_due_adhan_reminders_v1(t-interval '10 minutes');
 if not exists(select 1 from notification_events where kind='muezzin_duty' and user_id=assigned and data->>'assignmentSource'='default') then raise exception 'Default reminder fallback failed'; end if;
 perform start_live_broadcast_v1(assigned,m,'fajr',t,null,false,'livekit',null,null,'adhan-'||m||'-fajr-'||d);
 perform end_live_broadcast_v1(assigned,m,null);
 raise notice 'PASS: assigned/default/cover broadcast access, unassigned denial, start/end retries, listener reminders and live notification outbox';
end $$;
select public.test_operational_flows();

-- Capture protected schema definitions and data before applying the add-on.
create table public.compatibility_schema_baseline as
 select 'function:'||p.oid::regprocedure::text as key,md5(pg_get_functiondef(p.oid)) as digest from pg_proc p
 where p.pronamespace='public'::regnamespace and p.proname in ('start_live_broadcast_v1','end_live_broadcast_v1','enqueue_due_adhan_reminders_v1','enqueue_live_adhan_notification_v1')
 union all select 'policy:'||schemaname||'.'||tablename||'.'||policyname,md5(to_jsonb(p)::text) from pg_policies p where schemaname='public'
 union all select 'trigger:'||tgrelid::regclass::text||'.'||tgname,md5(pg_get_triggerdef(oid)) from pg_trigger where not tgisinternal;
create table public.compatibility_data_baseline(relation text primary key,rows jsonb);
do $$ declare n text; snapshot jsonb; begin
 foreach n in array array['prayer_times','staff_rota','muezzins','streams','adhans','notification_events','mosques'] loop
  execute format('select coalesce(jsonb_agg(to_jsonb(t) order by id),''[]'') from public.%I t',n) into snapshot;
  insert into compatibility_data_baseline values(n,snapshot);
 end loop;
end $$;
