\set ON_ERROR_STOP on
insert into users values ('00000000-0000-0000-0000-000000000001','main_admin'),('00000000-0000-0000-0000-000000000002','local_admin');
insert into profiles values ('00000000-0000-0000-0000-000000000001');
insert into mosques(id,name) values ('10000000-0000-0000-0000-000000000001','Test Mosque');
do $$
declare actor uuid := '00000000-0000-0000-0000-000000000001'; m uuid := '10000000-0000-0000-0000-000000000001';
 j uuid; imp uuid; n integer; caught boolean; claimed mosque_assistant_jobs;
 review jsonb := '{"websiteConfirmed":true,"timeZone":"Europe/London","profile":{"contact_email":{"value":"office@example.org","source_url":"https://example.org/contact","evidence":"Public office"}},"table":{"source_url":"https://example.org/timetable"}}';
 rows jsonb := '[{"date":"2026-09-05","fajr":"05:00","fajr_iqama":null,"dhuhr":"13:00","dhuhr_iqama":null,"asr":"16:00","asr_iqama":null,"maghrib":"19:30","maghrib_iqama":null,"isha":"21:00","isha_iqama":null}]';
begin
  if has_function_privilege('authenticated','public.publish_mosque_assistant(uuid,uuid,jsonb,jsonb)','execute') then raise exception 'Authenticated role can bypass the owner API'; end if;
  if has_table_privilege('authenticated','public.mosque_assistant_jobs','select') then raise exception 'Drafts are exposed'; end if;
  caught := false;
  begin perform enqueue_mosque_assistant('00000000-0000-0000-0000-000000000002','2026-09'); exception when others then caught:=true; end;
  if not caught then raise exception 'Local admin queued a scan'; end if;
  insert into prayer_times(mosque_id,date,fajr_iqama_time) values(m,'2026-09-05','2026-09-05 04:30:00+00');
  n:=enqueue_mosque_assistant(actor,'2026-09');
  if n<>1 or enqueue_mosque_assistant(actor,'2026-09')<>0 then raise exception 'Queue deduplication failed'; end if;
  select * into claimed from claim_mosque_assistant(); j:=claimed.id;
  if claimed.status<>'running' or claimed.attempts<>1 or claimed.lease_token is null then raise exception 'Claim failed'; end if;
  if exists(select 1 from claim_mosque_assistant()) then raise exception 'Claimed live job twice'; end if;
  update mosque_assistant_jobs set status='review' where id=j;
  imp:=publish_mosque_assistant(actor,j,review,rows);
  if (select fajr_adhan_time from prayer_times where mosque_id=m and date='2026-09-05') <> '2026-09-05 04:00:00+00'::timestamptz then raise exception 'BST conversion failed'; end if;
  if (select fajr_iqama_time from prayer_times where mosque_id=m and date='2026-09-05') <> '2026-09-05 04:30:00+00'::timestamptz then raise exception 'Missing iqama erased existing value'; end if;
  if (select contact_email from mosques where id=m)<>'office@example.org' then raise exception 'Profile was not published'; end if;
  if (select count(*) from prayer_schedule_import_rows where import_id=imp and previous_row is not null and published_row is not null)<>1 then raise exception 'Audit snapshots missing'; end if;
  if publish_mosque_assistant(actor,j,review,rows)<>imp then raise exception 'Publication is not idempotent'; end if;
  perform enqueue_mosque_assistant(actor,'2026-09'); select id into j from mosque_assistant_jobs where status='queued';
  update mosque_assistant_jobs set status='review' where id=j;
  update prayer_times set isha_adhan_time='2026-09-05 21:00:00+00' where mosque_id=m;
  caught:=false;
  begin perform publish_mosque_assistant(actor,j,review,rows); exception when others then caught:=sqlerrm like '%changed since%'; end;
  if not caught then raise exception 'Concurrent timetable edit was not protected'; end if;
  if (select status from mosque_assistant_jobs where id=j)<>'review' then raise exception 'Failed publish changed state'; end if;
  update mosque_assistant_jobs set status='rejected' where id=j;
  perform enqueue_mosque_assistant(actor,'2026-10'); select id into j from mosque_assistant_jobs where status='queued';
  update mosque_assistant_jobs set status='review' where id=j;
  caught:=false;
  begin perform publish_mosque_assistant(actor,j,review,'[{"date":"2026-10-25","fajr":"01:30","dhuhr":"12:30","asr":"15:00","maghrib":"17:00","isha":"19:00"}]'); exception when others then caught:=sqlerrm like '%ambiguous%'; end;
  if not caught then raise exception 'Repeated DST time was accepted'; end if;
  update mosque_assistant_jobs set status='rejected' where id=j;
  perform enqueue_mosque_assistant(actor,'2026-11'); select id into j from mosque_assistant_jobs where status='queued';
  update mosque_assistant_jobs set status='review' where id=j;
  perform publish_mosque_assistant(actor,j,review,'[{"date":"2026-11-05","fajr":"05:00","dhuhr":"12:30","asr":"15:00","maghrib":"17:00","isha":"19:00"}]');
  if (select fajr_adhan_time from prayer_times where mosque_id=m and date='2026-11-05')<>'2026-11-05 05:00:00+00'::timestamptz then raise exception 'Winter timezone conversion failed'; end if;
  perform enqueue_mosque_assistant(actor,'2026-12'); select id into j from mosque_assistant_jobs where status='queued';
  update mosque_assistant_jobs set status='running',attempts=2,lease_until=now()-interval '1 minute' where id=j;
  select * into claimed from claim_mosque_assistant();
  if claimed.id<>j or claimed.attempts<>3 then raise exception 'Expired lease was not recovered'; end if;
  update mosque_assistant_jobs set lease_until=now()-interval '1 minute' where id=j;
  perform claim_mosque_assistant();
  if (select status from mosque_assistant_jobs where id=j)<>'failed' then raise exception 'Lease retries were not bounded'; end if;
  raise notice 'PASS: owner authorization, private drafts, queue deduplication, claims, atomic publish, DST, preserved iqama, snapshots, stale edits and lease recovery';
end $$;
